data:
  num_workers: 8
  batch_size: 64

  dataset:
    dataset_name: waterbirds
    load_path: /hdd2/dyah/sicheng_test/causal-x-ws/e2e/artifacts/extracted_features/waterbirds/CLIP/2_class_FA_CLEAN
    n_orig_features: 769
    n_pac_features: 6
    tasks: ["irm"]

train: True

model:
  active_lfs:
    notears: ['NoTears Sobolev']
    classic: ['PC','FCI','Exact Search','MMPC','GS','IAMB','Inter_IAMB','Lingam',]
    pycausal: ['fges','rfci','pc-all','fask',]
  output_model: CLIPMLP
  fuser: 'COmnivore_V'
  alpha: 2
  

opt:
  epochs: 300
  lr: 3.e-5
  l2: 0.0
  dropout: 0.2
  n_layers: 1
  comnivore_v:
    all_negative_balance: [0.1,1.0,0.1]
    snorkel_ep: 500
    snorkel_lr: 1.e-3
  comnivore_g:
    n_triplets: 7 
    min_iters: 100
    max_iters: 10000
    step: 100

pipeline:
  baseline: True
  indiv_training: False
  fused_causal: True

utils:
  log_freq: 10