data:
  num_workers: 8
  batch_size: 32

  dataset:
    dataset_name: celebA
    root_path: ./artifacts/extacted_features
    feature_path: CLIP/2_class_FA_LESS
    load_path: /hdd2/dyah/sicheng_test/causal-x-ws/e2e/artifacts/extracted_features/celebA/CLIP/2_class_FA_LESS
    n_orig_features: 769
    n_pac_features: 4
    tasks: ["orig"]
    images_path: /hdd2/wilds_data/celebA_v1.0
    metadata_file_name: "list_eval_partition.csv"

model:
  active_lfs:
    notears: ['NoTears Sobolev']
    classic: ['PC','FCI','Exact Search','MMPC','GS','IAMB','Inter_IAMB','Lingam',]
    pycausal: ['fges','rfci','pc-all','fask',]
  output_model: CLIPMLP
  fuser: 'COmnivore_V'

opt:
  epochs: 150
  lr: 1.e-5
  l2: 0.1
  dropout: 0.0
  comnivore_v:
    all_negative_balance: [0.01,1.0,0.01]
    snorkel_ep: 1000
    snorkel_lr: 1.e-4
  comnivore_g:
    n_triplets: 7 
    min_iters: 100
    max_iters: 10000
    step: 100

pipeline:
  baseline: False
  indiv_training: False
  fused_causal: True

utils:
  log_freq: 15
  n_save_images: 100
