data:
  num_workers: 8
  batch_size: 16

  dataset:
    dataset_name: waterbirds
    root_path: ./artifac1.ts/extracted_features
    feature_path: CLIP/2_class_FA_CLEAN
    load_path: /hdd2/dyah/sicheng_test/causal-x-ws/e2e/artifacts/extracted_features/waterbirds/CLIP/2_class_FA_CLEAN
    n_orig_features: 769
    n_pac_features: 6
    tasks: ["segment"]

extraction_pipeline:
  reshape_size: 224
  extraction_batch_size: 128
  z_hidden: 5
  extractor_model: 'CLIP'

model:
  active_lfs:
    notears: ['NoTears Sobolev']
    classic: ['PC','FCI','Exact Search','MMPC','GS','IAMB','Inter_IAMB','Lingam',]
    pycausal: ['fges','rfci','pc-all','fask',]
  output_model: CLIPMLP
  fuser: 'COmnivore_V'
  alpha: 2

opt:
  epochs: 500
  lr: 7.5e-6
  l2: 0.1
  dropout: 0.1
  comnivore_v:
    all_negative_balance: [0.1,1.0,0.1]
    snorkel_ep: 500
    snorkel_lr: 1.e-3
  comnivore_g:
    n_triplets: 7 
    min_iters: 100
    max_iters: 10000
    step: 100

pipeline:
  baseline: False
  indiv_training: False
  fused_causal: True

utils:
  log_freq: 25
